/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kasir.*;
import login.Config;

/**
 *
 * @author yogan
 */
public class edit_user extends javax.swing.JFrame {

    /**
     * Creates new form transaksi
     */
    public edit_user() {
        initComponents();
        load_table();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txthp = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        txtpw = new javax.swing.JPasswordField();
        btn_edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel2.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/back_40px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(1270, 60, 50, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 36, 36));
        jLabel2.setText("Admin");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 60, 160, 50);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 36, 36));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/password_25px.png"))); // NOI18N
        jLabel10.setText("Password");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(760, 230, 160, 30);

        txtalamat.setBackground(new java.awt.Color(236, 236, 236));
        txtalamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtalamat.setForeground(new java.awt.Color(36, 36, 36));
        txtalamat.setBorder(null);
        txtalamat.setOpaque(false);
        jPanel2.add(txtalamat);
        txtalamat.setBounds(480, 230, 240, 30);

        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18);
        jLabel18.setBounds(40, 430, 60, 50);

        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel19);
        jLabel19.setBounds(40, 194, 60, 50);

        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20);
        jLabel20.setBounds(40, 270, 60, 50);

        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21);
        jLabel21.setBounds(40, 350, 60, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Logout_40px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9);
        jLabel9.setBounds(240, 60, 40, 50);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 36, 36));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user_tag_25px.png"))); // NOI18N
        jLabel11.setText("ID User");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(320, 150, 160, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(36, 36, 36));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user_25px.png"))); // NOI18N
        jLabel12.setText("Nama User");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(320, 190, 160, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(36, 36, 36));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/address_25px.png"))); // NOI18N
        jLabel13.setText("Alamat");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(320, 230, 160, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(36, 36, 36));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/address_book_25px.png"))); // NOI18N
        jLabel14.setText("Telepon");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(760, 150, 160, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 36, 36));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user_rights_25px.png"))); // NOI18N
        jLabel15.setText("User Tipe");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(760, 190, 160, 30);

        txtuser.setBackground(new java.awt.Color(236, 236, 236));
        txtuser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(36, 36, 36));
        txtuser.setBorder(null);
        txtuser.setOpaque(false);
        jPanel2.add(txtuser);
        txtuser.setBounds(480, 150, 240, 30);

        txtnama.setBackground(new java.awt.Color(236, 236, 236));
        txtnama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtnama.setForeground(new java.awt.Color(36, 36, 36));
        txtnama.setBorder(null);
        txtnama.setOpaque(false);
        jPanel2.add(txtnama);
        txtnama.setBounds(480, 190, 240, 30);

        txthp.setBackground(new java.awt.Color(236, 236, 236));
        txthp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txthp.setForeground(new java.awt.Color(36, 36, 36));
        txthp.setBorder(null);
        txthp.setOpaque(false);
        jPanel2.add(txthp);
        txthp.setBounds(920, 150, 240, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(36, 36, 36));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kasir", "admin" }));
        jComboBox1.setBorder(null);
        jComboBox1.setOpaque(false);
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(910, 190, 260, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(320, 320, 980, 370);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 36, 36));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/search_25px.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(1270, 280, 30, 30);

        jTextField1.setBackground(new java.awt.Color(236, 236, 236));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(36, 36, 36));
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(1000, 280, 270, 30);

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/trash_25px.png"))); // NOI18N
        btn_delete.setBorder(null);
        btn_delete.setBorderPainted(false);
        btn_delete.setOpaque(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_delete);
        btn_delete.setBounds(1250, 210, 60, 50);

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/plus_math_25px.png"))); // NOI18N
        btn_tambah.setBorder(null);
        btn_tambah.setBorderPainted(false);
        btn_tambah.setOpaque(false);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel2.add(btn_tambah);
        btn_tambah.setBounds(1180, 150, 60, 50);

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/clear_symbol_25px.png"))); // NOI18N
        btn_clear.setBorder(null);
        btn_clear.setBorderPainted(false);
        btn_clear.setOpaque(false);
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear);
        btn_clear.setBounds(1250, 150, 60, 50);

        txtpw.setBackground(new java.awt.Color(240, 240, 240));
        txtpw.setBorder(null);
        txtpw.setPreferredSize(new java.awt.Dimension(0, 25));
        jPanel2.add(txtpw);
        txtpw.setBounds(920, 230, 240, 30);

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/edit_25px.png"))); // NOI18N
        btn_edit.setBorder(null);
        btn_edit.setBorderPainted(false);
        btn_edit.setOpaque(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel2.add(btn_edit);
        btn_edit.setBounds(1180, 210, 60, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user_admin.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="DELETE FROM anggota where id_pengguna='"+txtnama.getText()+"'";
            String sqll ="DELETE FROM akun where id_pengguna='"+txtnama.getText()+"'";
        java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.PreparedStatement pstl=conn.prepareStatement(sqll);
            pst.execute();
            pstl.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
        load_table();
        kosong();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO akun VALUES ('"+txtuser.getText()+"','"
                    +txtpw.getText()+"')";
            String sqll = "INSERT INTO anggota VALUES ('"+txtuser.getText()+"','"
                    +txtnama.getText()+"','"+txtalamat.getText()+"','"+
                    txthp.getText()+"','"+jComboBox1.getSelectedItem()+"')";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.PreparedStatement pstl=conn.prepareStatement(sqll);
            pst.execute();
            pstl.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
        load_table();
        kosong();        
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new admin.menu_admin().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new login.login().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new admin.edit_barang().setVisible(true);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new admin.edit_supplier().setVisible(true);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new admin.riwayat_admin().setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE anggota INNER JOIN akun ON akun.id_pengguna = anggota.id_pengguna "
                    + "SET nama_anggota = '"+txtnama.getText()+"', alamat_anggota = '"
                    +txtalamat.getText()+"', telp_anggota = '"
                    +txthp.getText()+"', tipe_anggota = '"+jComboBox1.getSelectedItem()
                    +"'WHERE anggota.id_pengguna = '"+txtuser.getText()+"'";
            String sqll ="UPDATE akun INNER JOIN mhs ON mhs.nim = akun.nim "
                    +"SET password = '"+txtpw.getText()
                    +"'WHERE akun.id_pengguna = '"+txtuser.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.PreparedStatement pstl=conn.prepareStatement(sqll);
            pst.execute();
            pstl.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data gagal " +e.getMessage());
        } 
        load_table();
        kosong();
    }//GEN-LAST:event_btn_editActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String id = jTable1.getValueAt(baris, 1).toString();
        txtuser.setText(id);
        txtuser.disable();
        if (jTable1.getValueAt(baris, 2)==null) {
            txtnama.setText("");
        } else {
            txtnama.setText(jTable1.getValueAt(baris, 2).toString());
        }
        if (jTable1.getValueAt(baris, 3)==null) {
            txtalamat.setText("");
        } else {
            txtalamat.setText(jTable1.getValueAt(baris, 3).toString());
        }
        if (jTable1.getValueAt(baris, 4)==null) {
            txthp.setText("");
        } else {
            txthp.setText(jTable1.getValueAt(baris, 4).toString());
        }
        if (jTable1.getValueAt(baris, 5)==null) {
            jComboBox1.setSelectedItem(this);
        } else {
            jComboBox1.setSelectedItem(jTable1.getValueAt(baris, 5).toString());
        }
        if (jTable1.getValueAt(baris, 6)==null) {
            txtpw.setText("");
        } else {
            txtpw.setText(jTable1.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void load_table() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("ID User");
    model.addColumn("Nama");
    model.addColumn("Alamat");
    model.addColumn("No. Hp");
    model.addColumn("Tipe User");
    model.addColumn("Password");
    
    try {
        int no=1;
        String sql = "select * from anggota join akun on anggota.id_pengguna = akun.id_pengguna";
        java.sql.Connection conn=(Connection)Config.configDB();
        java.sql.Statement stm=conn.createStatement();
        java.sql.ResultSet res=stm.executeQuery(sql);
        while(res.next()){
            model.addRow (new Object[] {no++,res.getString(1),
                res.getString(2),res.getString(3),res.getString(4),
                res.getString(5),res.getString(7)
            });
        }
        jTable1.setModel(model);
    } catch (Exception e) {
        
    }
}
    private void kosong(){
    txtuser.enable();
    txtnama.setText(null);
    txtalamat.setText(null);
    txthp.setText(null);
    txtpw.setText(null);
    jComboBox1.setSelectedItem(this);
}
//    private void JComboBox() {
//    DefaultComboBoxModel model = new DefaultComboBoxModel();
    
//}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtnama;
    private javax.swing.JPasswordField txtpw;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
